language: node_js

go:
    - "1.15.2"

node_js:
    - node

install:
    - go version
    - npm install
    - npx node-gyp configure
    - npx node-gyp rebuild

script:
    - npm test
    - cat ./coverage/lcov.info | npx coveralls
